### ISSUE TITLE
Improve filtering

### ISSUE THREAD

**Issue by robredpath** [TalkAboutLocal/local-news-engine#14]
This means being able to:
- See only results that relate to wards or groups of wards that I care about
- Remove data sources that I don't care about, eg list of celebrities. I'd expect a record that only existed because it matched two data sources to disappear from the results if that went down to just one. 

This should be exposed to the user in the interface

**Comment by Bjwebb** [comment]
Just clicking around on master, and spotted a couple of things:

> I'd expect a record that only existed because it matched two data sources to disappear from the results if that went down to just one.

This isn't the case atm. (Although I'm not clear if this is the behaviour that we want - being able to filter down to everything that includes one particular data source (and matches any other) sounds like a usecase people might actually have). 

Also, when I filter out a data source, it still appears as the "Latest Appearance".

**Comment by robredpath** [comment]
> This isn't the case atm.

Yeah, I talked with @kindly about this at length and I think the behaviour of saying "these are the things I'm interested in" rather than "show me everything but remove these things" makes more sense 

> Also, when I filter out a data source, it still appears as the "Latest Appearance".

We know that this is a limitation and I gather it's tricky to address. Maybe iteration 3?
