### ISSUE TITLE
Set up analytics

### ISSUE THREAD

**Issue by robredpath** [TalkAboutLocal/local-news-engine#16]
We want to: 
- Set up a server to receive analytics data from whenever the file(s) are used (on a machine that's connected to the internet)
- Update the file(s) to report basic analytics back to the server

**Comment by Bjwebb** [comment]
I've set up a "Local News Engine" site on our existing piwik analytics server. An assumption of me doing this is we'll be careful not to send any sensitive data in the analytics.

I've made a commit to add the piwik tracking code. Out of the box this does some stuff for us, but isn't very useful. The next step is to use piwik's javascript calls to add extra custom analytics info. http://developer.piwik.org/guides/tracking-javascript-guide

**Comment by Bjwebb** [comment]
Currently my local copy of LNE doesn't have the courts data in it, so I can be sure not to send sensitive data up to piwik whilst setting it up.

Currently piwik is set up to record the fragment from the URL. This would include people's search terms. Is this a problem?

**Comment by Bjwebb** [comment]
Discussed on standup this morning - we want to avoid sending or storing actual search terms. Metadata about number of searches etc. would be useful though.

**Comment by Bjwebb** [comment]
@robredpath I think we said yesterday that you should be able to write up a spec of broadly what analytics we might want.

**Comment by robredpath** [comment]
I've had another read through the contract and I think it'd be good to have things along the lines of:
- How often people use LNE. We should probably be conscious of people's tendency to leave things open in the background, especially if they don't have a memorable address, so if there's space for some sort of timeout, that would be cool. But, at a minimum, 'on how many days did they use LNE' would be ok 
- Some sort of idea of what they did. How many searches did they make? How many times did they use filters? How many times did they click the 'full record' button? How much time did they spend just scrolling, and when? How many pages of results did they click through before doing something else? 

@Bjwebb ^^

**Comment by Bjwebb** [comment]
There's now a pull request for the work in this issue https://github.com/TalkAboutLocal/local-news-engine/pull/26 and a seperate issue for further tasks https://github.com/TalkAboutLocal/local-news-engine/issues/49
