### ISSUE TITLE
Islington Tribune entity extraction

### ISSUE THREAD

**Issue by robredpath** [TalkAboutLocal/local-news-engine#42]
http://www.islingtontribune.com/

**Comment by Bjwebb** [comment]
Looks like the same underlying system as CNJ, so should be pretty doable.

Might want to wait until the current CNJ work is done and merged https://github.com/TalkAboutLocal/local-news-engine/pull/27

**Comment by Bjwebb** [comment]
I've set wget running on the islingtontribune site.

**Comment by Bjwebb** [comment]
This was done.
