### ISSUE TITLE
Finish analytics

### ISSUE THREAD

**Issue by robredpath** [TalkAboutLocal/local-news-engine#49]
....whatever that means!

**Comment by Bjwebb** [comment]
This is basically finishing off https://github.com/TalkAboutLocal/local-news-engine/issues/16

**Comment by Bjwebb** [comment]
There's now a pull request for most of my work so far https://github.com/TalkAboutLocal/local-news-engine/pull/26

Remaining tasks:
- [x] Set up custom dimensions
- [x] Disable heartbeat timer
- [x] Record the date the page was generated
- [x] Track events when people open modals/expand records
- [x] Discuss whether this does what we need
- [x] Revert user tracking commit, we won't use this
- [x] Discuss content tracking https://github.com/TalkAboutLocal/local-news-engine/pull/58
- [x] Also set up analytics for areas.html https://github.com/TalkAboutLocal/local-news-engine/issues/57

**Comment by Bjwebb** [comment]
There's now a description of these changes in the pull request https://github.com/TalkAboutLocal/local-news-engine/pull/26
