### ISSUE TITLE
Tracking visitors with multiple visits in piwik

### ISSUE THREAD

**Issue by Bjwebb** [TalkAboutLocal/local-news-engine#60]
Following on from https://github.com/TalkAboutLocal/local-news-engine/pull/26

I've notice that there aren't in fact any visitors with multiple visits in piwik (unless we actually set a user ID) for LNE - but it's fine for other projects.

Piwik should be [setting a cookie](https://piwik.org/faq/general/faq_21418/) but it looks like this doesn't work for file:// - for chrome at least https://bugs.chromium.org/p/chromium/issues/detail?id=535

**Comment by Bjwebb** [comment]
Apparently firefox doesn't have this same problem.

**Comment by robredpath** [comment]
We're calling this a limitation of the prototype and proposing to not fix it
