### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by robredpath** [TalkAboutLocal/local-news-engine#78]
- [x] length of time that search actually takes
- [x] log whether it's the courts data version
- [x] check whether analytics are still being tracked correctly
- [x] can we also log how long the initial page load takes?

**Comment by Bjwebb** [comment]
Piwik can log how long the search actually takes, but it we only display a mean, min, and max. If we want more though, we can pull the data out with our own database query:
`select server_time, custom_float, custom_dimension_4 from piwik_log_link_visit_action WHERE idsite=10 ORDER BY server_time DESC LIMIT 10;`

**Comment by Bjwebb** [comment]
I'm also tracking the initial page load time, because I think even if we don't want this as a metric it may help with our debugging.

**Comment by Bjwebb** [comment]
The tasks in this issue are done now, but I think there's an outstanding analytics related task of making user all this tracking is applied correctly to wards.html also.

**Comment by robredpath** [comment]
Thanks @Bjwebb , added #87 to carry that on
