### ISSUE TITLE
CNJ stories duplicated

### ISSUE THREAD

**Issue by robredpath** [TalkAboutLocal/local-news-engine#81]
CNJ stories are duplicated in results

**Comment by robredpath** [comment]
This is quite a low-priority bug as it's probably just aesthetic but we're going to look into it at least to know what's causing it and how much it's likely to be an issue in the future

**Comment by Bjwebb** [comment]
Looks like I'm just not de-duplicating when the same entity appears twice in an article, so this should be fixed by a one line change.

I need to rerun the entity extraction anyway due to https://github.com/TalkAboutLocal/local-news-engine/issues/68
